services:
  db:
    build: ./database
    restart: unless-stopped
    environment:
      POSTGRES_DB: rempy
      POSTGRES_USER: rempy
      POSTGRES_PASSWORD: rempy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"          
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rempy"]
      interval: 5s
      timeout: 5s
      retries: 5

  back:
    build: ./back
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/app                      
      - ./back/media:/app/media           
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "dev-secret-key-change-in-prod"
      POSTGRES_DB: rempy
      POSTGRES_USER: rempy
      POSTGRES_PASSWORD: rempy
      POSTGRES_HOST: db
      PYTHONUNBUFFERED: 1  

    depends_on:
      db:
        condition: service_healthy        

  front:
    build: ./front
    restart: unless-stopped
    ports:
      - "8050:8050"
    volumes:
      - ./front:/app
      - ./media:/app/media
    depends_on:
      - back

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
    - db

volumes:
  postgres_data: